### ISSUE TITLE
Multiple recipients with the same type not works as expected

### ISSUE THREAD

**Issue by neutronth** [neutronth/kpt-update-ksops-secrets#16]
### Problem
For the following configuration, the `kpt-update-ksops-secrets` should generate the encrypted files for both recipients but only one is generated.

```
apiVersion: fn.kpt.dev/v1alpha1
kind: UpdateKSopsSecrets
metadata:
  name: docker-pullsecret
secret:
  type: kubernetes.io/dockerconfigjson
  references:
    - unencrypted-secrets
  items:
    - .dockerconfigjson
recipients:
  - type: pgp
    recipient: F532DA10E563EE84440977A19D0470BDA6CDC457
    publicKeySecretReference:
      name: gpg-publickeys
      key: F532DA10E563EE84440977A19D0470BDA6CDC457.gpg
  - type: pgp
    recipient: DD3A2B7A09E672C7017467BD1AABEEADF4673F1B
    publicKeySecretReference:
      name: gpg-publickeys
      key: DD3A2B7A09E672C7017467BD1AABEEADF4673F1B.gpg
```
### Expected
* The encrypted files should be generated for all recipients properly.
