### ISSUE TITLE
Avoid double encryption in case the user set unencrypted secrets name as same as the generated secret name

### ISSUE THREAD

**Issue by neutronth** [neutronth/kpt-update-ksops-secrets#20]
```yaml
apiVersion: fn.kpt.dev/v1alpha1
kind: UpdateKSopsSecrets
metadata:
  name: config-token-secret
secret:
  type: Opaque
  references:
    - config-token-secret
  items:
    - config_token.json
```

For this setting and no provided preparing `config-token-secret` Secret resource,
Kpt is feeding existing encrypted values into the update pipeline and caused a double encryption instead of encryption ignoring.

### Expected behavior
The updating pipeline should ignore the encryption for unprovided secrets references.
