### ISSUE TITLE
Valildate data in Secret

### ISSUE THREAD

**Issue by wingyplus** [neutronth/kpt-update-ksops-secrets#29]
Consider example below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: unencrypted-secrets
data:
  DATABASE_REPLICA_URL: ecto://username:password@host:port/db
```

This should not encrypt due because the `data` block expect value to be base64 encoded.
